name: Build, and publish docker image to ACR

on:
  push:
   branches:
     - master

jobs:
  build_and_publish_docker_image:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install repo2docker
      run: |
        python -m pip install --upgrade pip
        pip install jupyter-repo2docker 

    - name: Generate image name
      run: |
        chmod +x ./.github/workflows/generate_image_name
        echo "IMAGE_NAME=$(./.github/workflows/generate_image_name ${{ github.repository }} ${{ github.sha }} ${{ secrets.IMAGE_PREFIX }})" >> $GITHUB_ENV 
    
    - name: Configure Azure Credentials
      uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.ACR_NAME }}.azurecr.io
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}

    - name: Build docker image
      run: |
        jupyter-repo2docker --image $IMAGE_NAME --no-clean --no-run --user-name jovyan --user-id 1000 --push .