#!/usr/bin/env python3

import sys
import hashlib
import string
import escapism

def _safe_build_slug(build_slug, limit, hash_length=6):
    build_slug_hash = hashlib.sha256(build_slug.encode('utf-8')).hexdigest()
    safe_chars = set(string.ascii_letters + string.digits)
    def escape(s):
        return escapism.escape(s, safe=safe_chars, escape_char='-')
    build_slug = escape(build_slug)
    return '{name}-{hash}'.format(
        name=build_slug[:limit - hash_length - 1],
        hash=build_slug_hash[:hash_length],
    ).lower()


repo_name = sys.argv[1]
ref = sys.argv[2]
image_prefix = sys.argv[3]

build_slug = repo_name.replace('/', '-')
safe_build_slug = _safe_build_slug(build_slug, limit=255 - len(image_prefix))

image_name = '{prefix}{build_slug}:{ref}'.format(
  prefix=image_prefix,
  build_slug=safe_build_slug,
  ref=ref
).replace('_', '-').lower()

print(image_name)